-- Question 1
#Retrieve a list of all employees from Employees table whose salary is greater than ₹50,000.
select * from Employees where Salary > 50000;

-- Question 2
-- From Products table, get count and average price of all products in 'Mobile' category.
select count(*) ,avg(Price) from Products
where Category="Mobile";

-- Question 3
-- Find all orders placed in January 2023 from Orders table.
SELECT *
FROM Orders
WHERE Order_Date BETWEEN '2023-01-01' AND '2023-01-31';

-- Question 4
-- List all products with stock quantity less than 50.
SELECT * FROM products 
WHERE Stock_Quantity < 50;

-- Question 5
-- Find employees who joined the company in 2020.
SELECT *
FROM employees
WHERE YEAR(Hire_Date) = 2020;

-- Question 6
-- Get the total quantity of all orders.
SELECT SUM(Quantity) AS total_quantity
FROM Orders;


-- Question 7
-- List all products with price between ₹10,000 and ₹30,000.
SELECT * FROM Products
WHERE Price BETWEEN 10000 AND 30000;

-- Question 8
-- Find employees in 'IT' department.
SELECT * FROM Employees
WHERE Department='IT';

-- Question 9
-- Get all orders with quantity greater than 1.
SELECT * FROM orders
WHERE Quantity >1;

-- Question 10
-- Find products whose names start with 'Smart'.
SELECT * FROM products
WHERE Product_Name LIKE 'Smart%';

-- Question 11
-- JOIN Employees and Orders tables to get a list of employees who have  placed at least 2 orders.
SELECT e.Employee_ID,
       e.First_Name,
       e.Last_Name,
       COUNT(o.Order_ID) AS total_orders
FROM employees e
JOIN orders o
  ON e.Employee_ID = o.Employee_ID
GROUP BY e.Employee_ID, e.First_Name, e.Last_Name
HAVING COUNT(o.Order_ID) >= 2;

-- Question 12
-- Get number of employees and average salary for each department.
SELECT Department,
COUNT(Employee_ID) as employee_count ,
AVG (Salary) as avg_salary  FROM Employees
GROUP BY Department;

-- Question 13
-- Find the most expensive product in each category.
SELECT Product_ID, Product_Name, Category, Price
FROM (
    SELECT *,
           RANK() OVER (
               PARTITION BY Category
               ORDER BY Price DESC
           ) AS rnk
    FROM Products
) t
WHERE rnk = 1;

-- Question 14
-- List all products that have been ordered at least once.

SELECT DISTINCT p.*
FROM Products p
INNER JOIN Orders o
ON p.Product_ID = o.Product_ID;

-- Question 15
-- Find the total sales amount for each product category.

SELECT
    p.Category,
    SUM(o.Total_Amount) AS total_sales
FROM Products p
INNER JOIN Orders o
ON p.Product_ID = o.Product_ID
GROUP BY p.Category;

-- Question 16
-- List employees with their hire year and the number of years they've been with the company.
SELECT Employee_ID,
       First_Name,
       Last_Name,
       YEAR(Hire_Date) AS hire_year,
       TIMESTAMPDIFF(YEAR, Hire_Date, CURDATE()) AS years_with_company
FROM employees;

-- Question 17
-- Find the top 3 most expensive products.
SELECT Product_Name FROM Products
ORDER BY Price DESC
LIMIT 3;

-- Question 18
-- Find the average order value for each month in 2023.
SELECT 
    MONTH(Order_Date) AS Month,
    AVG(Total_Amount) AS Avg_Order_Value
FROM Orders
WHERE YEAR(Order_Date) = 2023
GROUP BY MONTH(Order_Date)
ORDER BY Month;


-- Question 19
-- List all employees who earn more than the average salary.
SELECT * FROM Employees
WHERE  Salary > (SELECT AVG(Salary) FROM Employees);


-- Question 20
-- Find products that have never been ordered.
SELECT p.*
FROM Products p
LEFT JOIN Orders o ON p.Product_ID = o.Product_ID
WHERE o.Order_ID IS NULL;

-- Question 21
-- Count the number of orders for each customer.
SELECT Customer_ID, COUNT(*) AS Number_of_Orders
FROM Orders
GROUP BY Customer_ID
ORDER BY Number_of_Orders DESC;


-- Question 22
-- Find the second highest salary among all employees.
SELECT MAX(Salary) AS Second_Highest_Salary
FROM Employees
WHERE Salary < (
    SELECT MAX(Salary)
    FROM Employees
);


-- Question 23
-- List all employees who are managers.
SELECT * FROM Employees
WHERE Position LIKE '%Manager';


-- Question 24
-- Find the total revenue generated by each product.
SELECT p.Product_ID,p.Product_Name,
SUM(o.Total_Amount) AS Total_Revenue
FROM Orders o
JOIN Products p ON o.Product_ID = p.Product_ID
GROUP BY p.Product_ID, p.Product_Name
ORDER BY Total_Revenue DESC;

-- Question 25
-- List customers who have placed orders for products in multiple categories
SELECT o.Customer_ID
FROM Orders o
JOIN Products p ON o.Product_ID = p.Product_ID
GROUP BY o.Customer_ID
HAVING COUNT(DISTINCT p.Category) > 1;


-- Question 26
-- Get a list of customers who have placed the highest value orders. Also show their total order amount.
SELECT Customer_ID,SUM(Total_Amount) AS Total_Order_Amount
FROM Orders
GROUP BY Customer_ID
ORDER BY Total_Order_Amount DESC
LIMIT 1;


-- Question 27
-- JOIN all three tables (Employees, Products, and Orders) to get a list of employees who have sold products in 'Laptop' category.
SELECT DISTINCT e.Employee_ID,
       e.First_Name,
       e.Last_Name
FROM employees e
JOIN orders o
  ON e.Employee_ID = o.Employee_ID
JOIN products p
  ON o.Product_ID = p.Product_ID
WHERE p.Category = 'Laptop';

-- Question 28
-- Find the month with the highest total sales in 2023.
SELECT MONTH(Order_Date) AS Month,
SUM(Total_Amount) AS Total_Sales
FROM Orders
WHERE YEAR(Order_Date) = 2023
GROUP BY MONTH(Order_Date)
ORDER BY Total_Sales DESC
LIMIT 1;


-- Question 29
-- Find the top 3 customers by total order value.
SELECT Customer_ID,
SUM(Total_Amount) AS Total_Order_Value 
FROM Orders
GROUP BY Customer_ID
ORDER BY Total_Order_Value DESC
LIMIT 3;


-- Question 30
-- Find the department with the highest average salary.
SELECT Department,
AVG(Salary) AS AVG_SALARY 
FROM Employees
GROUP BY Department
ORDER BY AVG_SALARY DESC
LIMIT 1;

-- Question 31
-- Find products that are frequently ordered together (customers who ordered product A also ordered product B).
SELECT o1.Product_ID AS Product_A,
o2.Product_ID AS Product_B,
COUNT(DISTINCT o1.Customer_ID) AS Number_of_Customers
FROM Orders o1
JOIN Orders o2 
ON o1.Customer_ID = o2.Customer_ID 
AND o1.Product_ID < o2.Product_ID
GROUP BY o1.Product_ID, o2.Product_ID
ORDER BY Number_of_Customers DESC;

-- Question 32
-- Calculate the running total of sales for each month in 2023.
SELECT MONTH(Order_Date) AS MONTH,
SUM(Total_Amount) AS Monthly_Sales,
SUM(SUM(Total_Amount)) OVER (ORDER BY  MONTH(Order_Date)) AS Running_Total
FROM Orders
WHERE YEAR(Order_Date) = 2023
GROUP BY MONTH(Order_Date)
ORDER BY MONTH;

-- Question 33
-- Find employees who have the highest salary in their department.
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY Department ORDER BY Salary DESC) AS Salary_Rank
    FROM Employees
) AS ranked_employees
WHERE Salary_Rank = 1;

-- Question 34
-- Find the top 3 selling products in each category.
SELECT Category, Product_Name, Total_Quantity_Sold
FROM (
    SELECT 
        p.Category,
        p.Product_Name,
        SUM(o.Quantity) AS Total_Quantity_Sold,
        ROW_NUMBER() OVER (PARTITION BY p.Category ORDER BY SUM(o.Quantity) DESC) AS rn
    FROM Orders o
    JOIN Products p ON o.Product_ID = p.Product_ID
    GROUP BY p.Category, p.Product_Name
) AS t
WHERE rn <= 3;


-- Question 35
-- Find customers who have not placed any orders in the last 30 days.
SELECT DISTINCT Customer_ID
FROM Orders
WHERE Customer_ID NOT IN (
    SELECT Customer_ID
    FROM Orders
    WHERE Order_Date >= DATE_SUB('2023-03-05', INTERVAL 30 DAY)
);

-- Question 36
-- Calculate the percentage of total sales contributed by each product category.
SELECT p.Category,
SUM(o.Total_Amount) AS Category_Sales,
ROUND(SUM(o.Total_Amount) / 
(SELECT SUM(Total_Amount) FROM Orders) * 100, 2) AS Percentage_of_Total
FROM Orders o
JOIN Products p ON o.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Percentage_of_Total DESC;


-- Question 37
-- Find the department with the most employees.
SELECT Department,COUNT(*)  AS Employee_Count
FROM Employees
GROUP BY Department
ORDER BY Employee_Count DESC
LIMIT 1;


-- Question 38
-- Find the month-over-month growth in sales for 2023.
SELECT 
    m1.Month,
    m1.Total_Sales,
    ROUND(
        (m1.Total_Sales - m2.Total_Sales) / m2.Total_Sales * 100,
        2
    ) AS MoM_Growth_Percent
FROM
(
    SELECT 
        MONTH(Order_Date) AS Month,
        SUM(Total_Amount) AS Total_Sales
    FROM Orders
    WHERE YEAR(Order_Date) = 2023
    GROUP BY MONTH(Order_Date)
) m1
JOIN
(
    SELECT 
        MONTH(Order_Date) AS Month,
        SUM(Total_Amount) AS Total_Sales
    FROM Orders
    WHERE YEAR(Order_Date) = 2023
    GROUP BY MONTH(Order_Date)
) m2
ON m1.Month = m2.Month + 1;
-- Question 39
-- Find employees who have been with the company longer than their manager.

SELECT e.Employee_ID,
       e.First_Name,
       e.Last_Name,
       e.Hire_Date AS employee_hire_date,
       m.First_Name AS manager_first_name,
       m.Last_Name AS manager_last_name,
       m.Hire_Date AS manager_hire_date
FROM employees e
JOIN employees m
  ON e.Manager_ID = m.Employee_ID
WHERE e.Hire_Date < m.Hire_Date;

-- Question 40
-- Find the most profitable product category (highest total revenue).
SELECT
    p.Category,
    SUM(o.Total_Amount) AS Total_Revenue
FROM Products p
JOIN Orders o
    ON p.Product_ID = o.Product_ID
GROUP BY p.Category
ORDER BY Total_Revenue DESC
LIMIT 1;

-- Question 41
-- Find customers who have purchased from multiple product categories.

SELECT o.Customer_ID
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY o.Customer_ID
HAVING COUNT(DISTINCT p.Category) > 1;

-- Question 42
-- Find the average order value for each customer who has placed more than 1 order.
SELECT Customer_ID,
AVG(Total_Amount) AS Average_Order_Value
FROM Orders
GROUP BY Customer_ID
HAVING COUNT(Order_ID) > 1;

-- Question 43
-- Find products that have been ordered by at least 3 different customers.

SELECT o.Product_ID
FROM Orders o
GROUP BY o.Product_ID
HAVING COUNT(DISTINCT o.Customer_ID) >= 3;


-- Question 44
-- Find the rank of each employee by salary within their department.

SELECT
    Employee_ID,
    First_Name,
    Last_Name,
    Department,
    Salary,
    RANK() OVER (
        PARTITION BY Department
        ORDER BY Salary DESC
    ) AS Salary_Rank
FROM Employees;

-- Question 45
-- Find the cumulative total of orders for each month in 2023.
SELECT MONTH(Order_Date) AS Month,
SUM(Total_Amount) AS Monthly_Sales,
SUM(SUM(Total_Amount)) OVER (ORDER BY MONTH(Order_Date)) AS Cumulative_Sales
FROM Orders
WHERE YEAR(Order_Date) = 2023
GROUP BY MONTH(Order_Date)
ORDER BY Month;

-- Question 46
-- Find customers who have placed orders in consecutive months.
SELECT DISTINCT o1.Customer_ID
FROM Orders o1
JOIN Orders o2 
ON o1.Customer_ID = o2.Customer_ID
AND MONTH(o2.Order_Date) = MONTH(o1.Order_Date) + 1
AND YEAR(o2.Order_Date) = YEAR(o1.Order_Date);

-- Question 47
-- Find the department with the highest salary variance.
SELECT Department, VAR_SAMP(Salary) AS Salary_Variance
FROM Employees
GROUP BY Department
ORDER BY Salary_Variance DESC
LIMIT 1;

-- Question 48
-- Find products with prices above the average price in their category.
SELECT * FROM Products p
WHERE Price > (
    SELECT AVG(Price)
    FROM Products
    WHERE Category = p.Category
);

-- Question 49
-- Find the median salary for each department.
WITH RankedSalaries AS (
    SELECT 
        Department,
        Salary,
        ROW_NUMBER() OVER (PARTITION BY Department ORDER BY Salary) AS rn,
        COUNT(*) OVER (PARTITION BY Department) AS cnt
    FROM Employees
)
SELECT 
    Department,
    AVG(Salary) AS Median_Salary
FROM RankedSalaries
WHERE rn IN (FLOOR((cnt + 1) / 2), CEIL((cnt + 1) / 2))
GROUP BY Department;


-- Question 50
-- Find customers whose total order value is in the top 10% of all customers
WITH CustomerTotals AS (
    SELECT 
        Customer_ID,
        SUM(Total_Amount) AS Total_Order_Value
    FROM Orders
    GROUP BY Customer_ID
),
Ranked AS (
    SELECT 
        Customer_ID,
        Total_Order_Value,
        PERCENT_RANK() OVER (ORDER BY Total_Order_Value) AS pr
    FROM CustomerTotals
)
SELECT Customer_ID, Total_Order_Value
FROM Ranked
WHERE pr >= 0.9
ORDER BY Total_Order_Value DESC;















